### ISSUE TITLE
Unit Test Note

### ISSUE THREAD

**Issue by david1403** [sejyom/demo-project#2]
System.out.println( ) 은 콘솔에 출력되기 때문에 서버컴퓨터의 유닛테스트로 적합하지 않습니다. 뿐만 아니라 사람이 encrypted, decrypted 문자열을 확인할 수는 있지만, 복호화에 성공/실패를 했는지 시스템적으로 판별하기 어렵습니다. 
지금 하려는 작업이 
* 특정 String을 암호화
* 암호화한 String을 복호화
* 원래의 암호문과 암호화 -> 복호화 한 암호문이 동일하면 Pass, 다르면 Fail 하도록 설계
이때 사용하기 적합한 함수가 MatcherAssert.assertThat 입니다.

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

를 import 한 후에 사용하시면 됩니다. AssertThat 함수는 두 파라미터가 동일하면 테스트 통과, 다르면 테스트 실패합니다.
<img width="812" alt="image" src="https://github.com/sejyom/demo-project/assets/37106166/f71139a6-fd73-4981-8aa6-62e5a04a604d">

27번째줄만 넣으면 테스트가 통과, 28번째줄까지 넣으면 테스트가 실패합니다. 실제로 28번째 줄까지 넣고 실행한 결과
<img width="410" alt="image" src="https://github.com/sejyom/demo-project/assets/37106166/997f91f2-3d3f-4f10-89ac-202d3bde1d3d">

복호화한 "content" 가 반환되어야 하는데 다른 문자열이 들어가있다고 안내해줍니다.

**Comment by sejyom** [comment]
서버 컴에서 콘솔로 확인할 필요성은 못느껴 개발 단계에서 간단하게 확인하고자 System.out.println() 메서드를 썼어요! 패스워드 관련해서는 메신저로 알려드렸지만 덧붙여 궁금한 게 있으시면 말씀해 주세요 !!
