### ISSUE TITLE
@Autowired in HttpServletRequest

### ISSUE THREAD

**Issue by david1403** [sejyom/demo-project#3]
HttpServletRequest 는 Bean이 아니라서 Autowired가 동작하지 않을 것 같습니다. (실제로 제 로컬에서 에러 문구가 뜹니다)
<img width="536" alt="image" src="https://github.com/sejyom/demo-project/assets/37106166/019b6eb8-6c47-415a-bf89-816798cde33c">

modifiedBy가 수정한 사람을 직접적으로 가져오고 싶다면  이 구조를 따르는게 좋아보입니다. (Authentication authentication = SecurityContextHolder.getContext().getAuthentication(); 에서 정보 가져오고 BaseEntity도 구현)

(참고한 블로그 https://javacpro.tistory.com/85)

**Comment by sejyom** [comment]
넵 이 부분은 더 살펴볼게요!! 어쩐지 제 IDE에서도 경고 문구가 뜨더라고요 ..

**Comment by david1403** [comment]
넵, 저도 Jpa Auditing 과 관련해서 조금 더 살펴봐야겠네요. HttpServletRequest를 다른 클래스에서도 써야한다면 어떻게 해야할지도 고민해봐야겠에요. (아마도 SecurityContextHolder 를 조금 분석해보면 비슷하게 구현할 수 있겠죠..?)
