### ISSUE TITLE
프로젝트 패키지 구조에 대한 논의

### ISSUE THREAD

**Issue by david1403** [sejyom/demo-project#4]
web / common 도메인으로 나누는 것 까진 합의가 된 것 같아요. 그 중에서도 common 도메인의 경우
feature 별로 패키지를 나누었으면 좋겠는데 어떻게 생각하시나요? 예를들면 아래와 같은 형식으로..

* common
* featureA
    * model
        * entity
        * dto
    * repository
    * service
* featureB
  * entity
  * repsotory
  * service
* featureC

**Comment by sejyom** [comment]
네!! 저도 이렇게 생각했어요 이렇게 합시다 좋아유
